# Generated by Django 5.2 on 2025-05-23 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='rola',
            field=models.CharField(choices=[('klient', 'Klient'), ('pracownik', 'Pracownik'), ('admin', 'Admin')], default='klient', max_length=20),
        ),
    ]
