# Generated by Django 5.2 on 2025-04-27 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100)),
                ('cena', models.DecimalField(decimal_places=2, max_digits=10)),
                ('opis', models.TextField(blank=True)),
                ('kategoria', models.CharField(choices=[('zobacz wszystko', 'Zobacz wszystko'), ('obuwie', 'Obuwie'), ('nakrycia glowy', 'Nakrycia głowy'), ('bielizna', 'Bielizna'), ('skarpety', 'Skarpety'), ('bluzy', 'Bluzy'), ('swetry i kardigany', 'Swetry i kardigany'), ('koszulki', 'Koszulki'), ('koszule', 'Koszule'), ('spodnie', 'Spodnie'), ('jeansy', 'Jeansy'), ('spodenki', 'Spodenki'), ('plaszcze', 'Płaszcze'), ('kurtki', 'Kurtki'), ('kardigany', 'Kardigany'), ('garnitury i akcesoria', 'Garnitury i akcesoria')], default='zobacz wszystko', max_length=100)),
                ('zdjecie', models.ImageField(upload_to='products/')),
            ],
        ),
    ]
