# Generated by Django 5.2 on 2025-04-27 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='marka',
            field=models.CharField(default='Brak', max_length=100),
        ),
    ]
