# Generated by Django 5.2 on 2025-04-27 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0002_product_marka'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='zdjecie',
            field=models.ImageField(upload_to=''),
        ),
    ]
