# Generated by Django 5.2 on 2025-04-29 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0003_alter_product_zdjecie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='kategoria',
            field=models.CharField(choices=[('zobacz wszystko', 'Zobacz wszystko'), ('obuwie', 'Obuwie'), ('nakrycia glowy', 'Nakrycia głowy'), ('bielizna', 'Bielizna'), ('skarpety', 'Skarpety'), ('bluzy', 'Bluzy'), ('swetry i kardigany', 'Swetry i kardigany'), ('koszulki', 'Koszulki'), ('koszule', 'Koszule'), ('spodnie', 'Spodnie'), ('jeansy', 'Jeansy'), ('spodenki', 'Spodenki'), ('plaszcze', 'Płaszcze'), ('kurtki', 'Kurtki'), ('garnitury i akcesoria', 'Garnitury i akcesoria')], default='zobacz wszystko', max_length=100),
        ),
    ]
