# Generated by Django 5.2 on 2025-04-29 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0005_alter_product_kategoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField()),
                ('kwota', models.DecimalField(decimal_places=2, max_digits=10)),
                ('imie', models.CharField(max_length=50)),
                ('nazwisko', models.CharField(max_length=50)),
                ('adres', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('nrtel', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ilosc', models.IntegerField()),
                ('cena_jedn', models.DecimalField(decimal_places=2, max_digits=10)),
                ('produkt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Shop.product')),
                ('zamowienie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Shop.order')),
            ],
        ),
    ]
