# Generated by Django 5.2 on 2025-04-14 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ksiazka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tytul', models.CharField(max_length=200)),
                ('autor', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('do przeczytania', 'Do przeczytania'), ('czytam', 'Czytam'), ('przeczytana', 'Przeczytana')], default='do przeczytania', max_length=20)),
                ('data_dodania', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
