# Generated by Django 5.2 on 2025-05-14 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tytul', models.CharField(max_length=100)),
                ('opis', models.TextField(blank=True)),
                ('data_utworzenia', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('nowe', 'Nowe'), ('gotowe', 'Gotowe'), ('w trakcie', 'W trakcie'), ('odebrane', 'Odebrane')], default='nowe', max_length=100)),
                ('zdjecie', models.ImageField(blank=True, null=True, upload_to='ticket_zdjecia/')),
            ],
        ),
    ]
