# Generated by Django 5.2 on 2025-05-24 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_ticket_pracownik'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='uwagi',
            field=models.TextField(blank=True, null=True),
        ),
    ]
