# Generated by Django 5.2 on 2025-04-23 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wydatek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kwota', models.DecimalField(decimal_places=2, max_digits=10)),
                ('opis', models.TextField()),
                ('kategoria', models.CharField(choices=[('zywnosc', 'Żywność'), ('samochod', 'Samochód'), ('mieszkanie', 'Mieszkanie'), ('wlasne potrzeby', 'Własne potrzeby'), ('kredyt', 'Kredyt'), ('ogolna', 'Ogólna'), ('nagle wydatki', 'Nagłe wydatki')], default='ogólna', max_length=250)),
                ('data', models.DateField()),
            ],
        ),
    ]
