# Generated by Django 5.2 on 2025-04-13 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Zadanie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tytul', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('do zrobienia', 'Do zrobienia'), ('w trakcie', 'W trakcie'), ('zrobione', 'Zrobione')], default='do zrobienia', max_length=20)),
                ('data_dodania', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
