# Generated by Django 5.2 on 2025-04-14 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='zadanie',
            name='opis',
            field=models.TextField(blank=True),
        ),
    ]
